name: wx-map
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - boto3
  - click
  - gdal # needed?
  - jupyter
  - numpy
  - pygrib>=2.0.4
  - python=3
  - python-dateutil
  - requests
  - pip
  - pip:
    - python-language-server[all]
