name: wx-map
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - boto3
  - gdal # needed?
  - h5py
  - jupyter
  - pandas
  - pygrib>=2.0.4
  - python=3
  - requests
  - pip
  - pip:
    - python-language-server[all]
